GH-446: fix backtrace filter for site_ruby install
This patch fixes the filtering of MiniTest internals from backtraces
when MiniTest is bundled with Ruby itself or installed to site_ruby.

Here is the version of Ruby and Linux I'm using to reproduce this bug:

    $ ruby -v
    ruby 2.1.2p95 (2014-05-08) [x86_64-linux-gnu]

    $ cat /etc/issue
    Debian GNU/Linux jessie/sid \n \l

And here is a small Ruby test file that reproduces this bug when run:

    $ cat issue_446.rb
    require "minitest/autorun"

    class TestIssue446 < MiniTest::Unit::TestCase
      def test_backtrace_filtering
        i_am_intentionally_calling_an_undefined_method_here
      end
    end

When I run the test file with the MiniTest that comes bundled with Ruby
itself, the bug is reproduced as shown below.  Notice how the backtrace
exposes MiniTest's internals to the user; this should not be happening.

    $ ruby issue_446.rb
    Run options: --seed 48392

    # Running tests:

    E

    Finished tests in 0.000979s, 1021.1084 tests/s, 0.0000 assertions/s.

      1) Error:
    TestIssue446#test_backtrace_filtering:
    NameError: undefined local variable or method `i_am_intentionally_calling_an_undefined_method_here' for #<TestIssue446:0x000000024576d8>
        issue_446.rb:5:in `test_backtrace_filtering'
        /usr/lib/ruby/2.1.0/minitest/unit.rb:1265:in `run'
        /usr/lib/ruby/2.1.0/minitest/unit.rb:940:in `block in _run_suite'
        /usr/lib/ruby/2.1.0/minitest/unit.rb:933:in `map'
        /usr/lib/ruby/2.1.0/minitest/unit.rb:933:in `_run_suite'
        /usr/lib/ruby/2.1.0/minitest/unit.rb:914:in `block in _run_suites'
        /usr/lib/ruby/2.1.0/minitest/unit.rb:914:in `map'
        /usr/lib/ruby/2.1.0/minitest/unit.rb:914:in `_run_suites'
        /usr/lib/ruby/2.1.0/minitest/unit.rb:884:in `_run_anything'
        /usr/lib/ruby/2.1.0/minitest/unit.rb:1092:in `run_tests'
        /usr/lib/ruby/2.1.0/minitest/unit.rb:1079:in `block in _run'
        /usr/lib/ruby/2.1.0/minitest/unit.rb:1078:in `each'
        /usr/lib/ruby/2.1.0/minitest/unit.rb:1078:in `_run'
        /usr/lib/ruby/2.1.0/minitest/unit.rb:1066:in `run'
        /usr/lib/ruby/2.1.0/minitest/unit.rb:802:in `block in autorun'

    1 tests, 0 assertions, 0 failures, 1 errors, 0 skips
    exit 1

In contrast, when I run the test file with this patch applied, the bug
no longer occurs, as shown below.  Notice how the backtrace no longer
exposes MiniTest's internals; this is how it should be working. :-)

    $ ruby -Ilib issue_446.rb
    MiniTest::Unit::TestCase is now Minitest::Test. From issue_446.rb:3:in `<main>'
    Run options: --seed 43907

    # Running:

    E

    Finished in 0.001838s, 543.9749 runs/s, 0.0000 assertions/s.

      1) Error:
    TestIssue446#test_backtrace_filtering:
    NameError: undefined local variable or method `i_am_intentionally_calling_an_undefined_method_here' for #<TestIssue446:0x00000000fa66f8>
        issue_446.rb:5:in `test_backtrace_filtering'

    1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
    exit 1