Support the new message format of NameError in Ruby 3.3
This change accepts the following change of the message of NameError in
a test.

```
old: undefined method `write' for nil:NilClass
new: undefined method `write' for nil
```